### ISSUE TITLE
Frecuencies vs. Frequencies spelling error.

### ISSUE THREAD

**Issue by xgpt** [juanerasmoe/pmTrans#7]
Spanish vs. English. 

Please update the spelling in the code. I'm going to try, but I'm having issues understanding it all, I'm not really a coder, I just submit a lot of github issues with GUI/UX stuff.

**Comment by baracunatana** [comment]
Testing and submitting bugs is a great contribution.

Can you tell me where exactly is the misspelling so I can correct it?

**Comment by buddybu** [comment]
config.java -- lines 254 and 288.  

I would go further and suggest updating the spelling of the variables and constants that use frecuency as well:
Config.java -- line 167:  LOOP_FRECUENCY
Config.java -- line 168:  LOOP_FRECUENCY_DEFAULT
pmTrans.java -- line 141:  final int frecuency

**Comment by patiencedaur** [comment]
Looks like the spelling error has been fixed in this pull request: https://github.com/baracunatana/pmTrans/pull/8
